version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres_pwd
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
